name: MobHeads
main: com.cyber.mobheads.Main
version: 5.1
authors:
    - CyberDrain
    - Zombie_Striker
    - Lord_Lofi
    - "A few contributors who did not fill their names here"
api-version: 26.2
description: Allows players to behead mobs and other players!
commands:
    mobheads:
        description: Main command with several sub commands
        aliases: [mh, mobhead]
softdepend:
    - WorldGuard